# Generated by Django 3.2 on 2021-04-15 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directoryName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=30)),
                ('content', models.FileField(default='No file loaded', upload_to='')),
                ('uploadDate', models.DateTimeField()),
                ('inBin', models.BooleanField(default=False)),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.directory')),
            ],
        ),
        migrations.CreateModel(
            name='PrivateDisc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discName', models.CharField(max_length=20)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.bin')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(default='password', max_length=20)),
                ('privateDisc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.privatedisc')),
            ],
        ),
        migrations.CreateModel(
            name='PublicLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.URLField(max_length=50)),
                ('generationDate', models.DateTimeField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.file')),
            ],
        ),
        migrations.AddField(
            model_name='directory',
            name='disc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.privatedisc'),
        ),
    ]
