# Generated by Django 3.2 on 2021-04-15 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_fklsdl'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fklsdl',
        ),
    ]
