# Generated by Django 3.2 on 2021-04-08 13:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210407_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='content',
            field=models.FileField(default='No file loaded', upload_to=''),
        ),
        migrations.AlterField(
            model_name='file',
            name='uploadDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 8, 13, 13, 19, 898048, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='publiclink',
            name='generationDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 8, 13, 13, 19, 898048, tzinfo=utc)),
        ),
    ]
