# Generated by Django 3.2 on 2021-04-15 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_delete_fklsdl'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
