# Generated by Django 3.2 on 2021-04-15 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(default='password', max_length=20)),
                ('privateDisc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.privatedisc')),
            ],
        ),
    ]
