# Generated by Django 3.2 on 2021-04-13 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210408_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='password', max_length=20),
        ),
        migrations.AlterField(
            model_name='file',
            name='uploadDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='publiclink',
            name='generationDate',
            field=models.DateTimeField(),
        ),
    ]
