# Generated by Django 3.2 on 2021-04-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='isFavourite',
            field=models.BooleanField(default=False),
        ),
    ]
