# Generated by Django 3.2 on 2021-05-07 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_file_isfavourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatedisc',
            name='bin',
        ),
        migrations.DeleteModel(
            name='Bin',
        ),
    ]
