# Generated by Django 3.2 on 2021-05-07 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0007_auto_20210508_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='privateDisc',
        ),
        migrations.AlterField(
            model_name='directory',
            name='disc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='PrivateDisc',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
