# Generated by Django 3.2 on 2021-05-07 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20210508_0137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directory',
            old_name='disc',
            new_name='user',
        ),
    ]
